### ISSUE TITLE
Automations => LoadScreen Failure from System

### ISSUE THREAD

**Issue by Mecze** [qonversion/unity-sdk#263] opened 2024-10-30 16:19 UTC
Hi! I just got this error while testing Qonversion implementation.

`2024/10/30 16:59:03.116 6231 6231 Error Qonversion [Thread - main] loadScreen() -> Failed to start screen with id XXXXXXX with exception: java.lang.RuntimeException: Failure from system`

Here is my code:

```
    // Start is called before the first frame update
    void Start()
    {
        Log("Initializing...");
        QonversionConfig config = new QonversionConfigBuilder(
                "REDACTED",
                LaunchMode.SubscriptionManagement
            )
#if !PRODUCTION_BUILD
            .SetEnvironment(QonversionUnity.Environment.Sandbox)
#else
            .SetEnvironment(QonversionUnity.Environment.Production)
#endif            
            .Build();
        Qonversion.Initialize(config);
        Automations.GetSharedInstance().SetDelegate(this);

        StartCoroutine(_wait10seconds(() => {
            TestPaywall();
        }));
    }

    IEnumerator _wait10seconds(Action act)
    {
        yield return new WaitForSeconds(10);
        act?.Invoke();
    }

    void TestPaywall()
    {

        ScreenPresentationConfig config = new ScreenPresentationConfig(ScreenPresentationStyle.Popover, true);
        // Set configuration for all screens.
        Automations.GetSharedInstance().SetScreenPresentationConfig(config);

        QonversionUnity.Automations.GetSharedInstance().ShowScreen("XXXXX", (e) => {
            if (e != null)
            {
                Log("Error in paywall: " + e.Message);
            }
        });
    }
```

This is my mainTemplate.gradle

```
dependencies {   
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.activity:activity:1.6.1'
    implementation 'com.iabtcf:iabtcf-decoder:2.0.10'
// Android Resolver Dependencies Start
    implementation 'androidx.appcompat:appcompat:1.1.0' // Assets/Amazon/Scripts/Editor/AmazonDependencies.xml:4
    implementation 'androidx.recyclerview:recyclerview:1.2.1' // Assets/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:9
    implementation 'com.amazon.android:aps-sdk:9.+@aar' // Assets/Amazon/Scripts/Editor/AmazonDependencies.xml:9
    implementation 'com.android.installreferrer:installreferrer:2.2' // Assets/KrakenPlugins/AdjustKraken/AdjustWrapper/Editor/Dependencies.xml:6
    implementation 'com.android.support:customtabs:28.+' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:7
    implementation 'com.android.support:recyclerview-v7:28.+' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:6
    implementation 'com.applovin.mediation:amazon-tam-adapter:9.+@aar' // Assets/Amazon/Scripts/Mediations/AppLovinMediation/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:bytedance-adapter:5.9.0.6.0' // Assets/MaxSdk/Mediation/ByteDance/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:chartboost-adapter:9.7.0.1' // Assets/MaxSdk/Mediation/Chartboost/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:facebook-adapter:[6.17.0.0]' // Assets/MaxSdk/Mediation/Facebook/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:fyber-adapter:8.2.7.1' // Assets/MaxSdk/Mediation/Fyber/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:google-adapter:[23.2.0.0]' // Assets/MaxSdk/Mediation/Google/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:google-ad-manager-adapter:[23.2.0.0]' // Assets/MaxSdk/Mediation/GoogleAdManager/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:inmobi-adapter:10.7.4.0' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:ironsource-adapter:8.1.0.0.0' // Assets/MaxSdk/Mediation/IronSource/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:maio-adapter:1.1.16.3' // Assets/MaxSdk/Mediation/Maio/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:mintegral-adapter:16.7.71.0' // Assets/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:unityads-adapter:4.12.1.0' // Assets/MaxSdk/Mediation/UnityAds/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:vungle-adapter:7.4.0.0' // Assets/MaxSdk/Mediation/Vungle/Editor/Dependencies.xml:4
    implementation 'com.applovin:applovin-sdk:12.5.0' // Assets/MaxSdk/AppLovin/Editor/Dependencies.xml:4
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1' // Assets/KrakenPlugins/AdjustKraken/AdjustWrapper/Editor/Dependencies.xml:4
    implementation 'com.google.android.gms:play-services-appset:16.0.2' // Assets/KrakenPlugins/AdjustKraken/AdjustWrapper/Editor/Dependencies.xml:5
    implementation 'com.google.android.gms:play-services-base:18.2.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.android.play:core-common:2.0.0' // Assets/KrakenPlugins/RateCheck/Modules/InAppRate/GooglePlayPlugins/com.google.play.core/Editor/Dependencies.xml:3
    implementation 'com.google.android.play:review:2.0.0' // Assets/KrakenPlugins/RateCheck/Modules/InAppRate/GooglePlayPlugins/com.google.play.review/Editor/Dependencies.xml:3
    implementation 'com.google.android.ump:user-messaging-platform:2.1.0' // Assets/KrakenPlugins/KrakenCMP/GoogleCMP/Editor/Dependencies.xml:4
    implementation 'com.google.firebase:firebase-analytics:21.3.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:11.6.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:11.6.0' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-common:20.3.3' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-config:21.4.1' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:13
    implementation 'com.google.firebase:firebase-config-unity:11.6.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:20
    implementation 'com.google.firebase:firebase-crashlytics-ndk:18.4.3' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-unity:11.6.0' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.squareup.picasso:picasso:2.71828' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:5
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.11.1' // Packages/com.qonversion.unity/Editor/QonversionDependencies.xml:5
    implementation 'io.qonversion.sandwich:sandwich:5.1.6' // Packages/com.qonversion.unity/Editor/QonversionDependencies.xml:4
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.61' // Packages/com.qonversion.unity/Editor/QonversionDependencies.xml:6
// Android Resolver Dependencies End
**DEPS**}
```

Any tips here?
Thanks.

**Comment by Mecze** [comment] 2024-10-31 10:09
What are the accepted image sizes?
I tried another image around 250kb and the app just crashed.
It was a PNG with transparency and it was not POT.
I tried a 40kb one (also transparency and not POT) and it worked.
I got no warnings on the builder and I didn't find any reference in the docs.

**Comment by suriksarkisyan** [comment] 2024-10-31 10:32
Yes, we understand that the problem is unpleasant and not very obvious. Unfortunately, we cannot provide an exact size because the Android system cannot process it due to limitations on its side. I cannot give you an ETA, but we are already working on improvements. We will definitely get back to you with an update when we release it.

**Comment by Mecze** [comment] 2024-10-31 10:39
Understood. Thank you!

**Comment by suriksarkisyan** [comment] 2024-10-31 10:57
I will close this ticket, but as promised, I will return with an update when we release the fix. Feel free to open a new ticket or write here if needed.

**Closed by suriksarkisyan** 2024-10-31 10:57 UTC
Labels: awaiting answers
